In [1]:
print('hello world!')

hello world!


In [2]:
import numpy as np

l = [1, 2, 3, 4]
arr = np.array(l)

print('l', l) 
print('arr', arr)

l [1, 2, 3, 4]
arr [1 2 3 4]


In [3]:
l = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]
arr = np.array(l)
print(l)
print(arr)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [4]:
x = np.arange(1, 15)
print(x)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [5]:
x = np.zeros((3,4))
print(x)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [6]:
x = np.ones((3, 3))
print(x)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [10]:
r = np.random.rand(3)
print(r)
r = np.random.rand(3,4)
print(r)

[0.00442779 0.03760394 0.25512902]
[[0.97017375 0.56128636 0.47591534 0.93637387]
 [0.76511092 0.85973156 0.09393771 0.41294652]
 [0.55995592 0.67040158 0.53446288 0.5353036 ]]


In [18]:
r = np.random.randint(100)
print(r)
r = np.random.randint(100, 200)
print(r)
r = np.random.randint(100, 200, 5)
print(r)

99
139
[168 102 110 174 106]


In [19]:
r = np.random.randint(100, 200, (3,3))
print(r)

[[150 157 143]
 [125 157 158]
 [129 174 134]]
