In [4]:
print('hello world!')

hello world!


In [5]:
import numpy as np

l = [1, 2, 3, 4]
arr = np.array(l)

print('l', l) 
print('arr', arr)

l [1, 2, 3, 4]
arr [1 2 3 4]


In [6]:
l = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]
arr = np.array(l)
print(l)
print(arr)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [7]:
x = np.arange(1, 15)
print(x)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [8]:
x = np.zeros((3,4))
print(x)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [9]:
x = np.ones((3, 3))
print(x)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
